### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mintusf** [mintusf/land_cover_tracking#24]
## Summary
Describe this issue summary here.

## Goal
Describe the definition by which this issue will be closed.

## Todo
- [ ] how to setup environment
- [ ] how to start app
- [ ] app demo video

## Deadline
xx/xx

## Parent issue
None

## References
None

## Notes
None
