### ISSUE TITLE
Integrate with sentinel API

### ISSUE THREAD

**Issue by mintusf** [mintusf/land_cover_tracking#5]
## Summary
Describe this issue summary here.

## Goal
Describe the definition by which this issue will be closed.

## Todo
- [ ] add sentinel_api to env
- [ ] Prepare api call script
- [ ] show downloaded rasters

## Deadline
xx/xx

## Parent issue
None

## References
None

## Notes
None
